/**
 * @module tests/hana-trace-events
 * @description Playwright tests for the SAP HANA trace-event detectors
 * (deadlocks, out-of-memory, and delta-merge failures).
 *
 * The `hana_test-trace-events.zip` fixture (generated by the `fixtures-gen`
 * Rust crate) contains a single `indexserver_test.trc` with:
 *   - several record-lock deadlock cycles on `SAPHANADB:ADR2`,
 *   - one `OUT OF MEMORY` block on host `vmltmdbuspd01`, and
 *   - a batch of `rc = 2465` merge-token-exhaustion failures.
 */
import { test, expect } from './coverage-fixture.js';
import { uploadAndWaitForAnalysis, navigateToApp } from './test-helpers.js';

test.describe('SAP HANA trace events', () => {

  test.beforeEach(async ({ page }, testInfo) => {
    await navigateToApp(page, testInfo);
    await expect(page.locator('h1')).toContainText('RCA Tool');
  });

  test('detects deadlocks, OOM and delta-merge failures', async ({ page }) => {
    const html = await uploadAndWaitForAnalysis(page, 'hana_test-trace-events.zip');

    // Deadlocks section with the most-contended object.
    expect(html).toContain('SAP HANA Deadlocks');
    expect(html).toContain('Deadlocks detected');
    expect(html).toContain('Most contended objects');
    expect(html).toContain('SAPHANADB:ADR2');

    // Out-of-memory section with the failing host and executable.
    expect(html).toContain('SAP HANA Out-of-Memory');
    expect(html).toContain('Out-of-memory events');
    expect(html).toContain('vmltmdbuspd01');
    expect(html).toContain('hdbindexserver');

    // Delta-merge failures with merge-token exhaustion (rc=2465).
    expect(html).toContain('SAP HANA Delta-Merge Failures');
    expect(html).toContain('Merge-token exhaustion (rc=2465)');
  });
});
