/**
 * @module tests/hana
 * @description Playwright tests for the SAP HANA savepoint detector.
 *
 * The `hana_test-savepoints.zip` fixture (generated by the `fixtures-gen`
 * Rust crate) contains a single `indexserver_test.trc` with periodic
 * savepoints, replication snapshots, and one slow savepoint callback that
 * stalled for 12.4 s — which the analyzer surfaces as a warning.
 */
import { test, expect } from './coverage-fixture.js';
import { uploadAndWaitForAnalysis, navigateToApp } from './test-helpers.js';

test.describe('SAP HANA savepoints', () => {

  test.beforeEach(async ({ page }, testInfo) => {
    await navigateToApp(page, testInfo);
    await expect(page.locator('h1')).toContainText('RCA Tool');
  });

  test('detects savepoints and flags a slow savepoint callback', async ({ page }) => {
    const html = await uploadAndWaitForAnalysis(page, 'hana_test-savepoints.zip');

    // Savepoints section and summary rows are present.
    expect(html).toContain('SAP HANA Savepoints');
    expect(html).toContain('Periodic savepoints');
    expect(html).toContain('Snapshot savepoints');

    // The slow callback (12384 ms) is rendered as a stall warning.
    expect(html).toContain('HANA savepoint callback stalled for 12.4s');

    // The savepoint events table lists individual savepoint versions.
    expect(html).toContain('Savepoint events');
    expect(html).toContain('609685');
  });
});
