name: Run Tests

on:
  pull_request:
  workflow_dispatch:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '24'
        
    - name: Setup Emscripten
      uses: mymindstorm/setup-emsdk@v14
      with:
        version: 'latest'
        
    - name: Build WASM module
      run: |
        cd rca-tool/liblzma-wasm
        chmod +x build-liblzma-streaming.sh
        ./build-liblzma-streaming.sh
        
    - name: Install dependencies, Playwright and running tests
      run: npm ci
      working-directory: rca-tool/tests

    - name: Building fixtures
      run: |
        chmod +x create-fixtures.sh
        ./create-fixtures.sh
      working-directory: rca-tool/tests
 
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps msedge
      working-directory: rca-tool/tests
      
    - name: Run tests
      run: npm test
      working-directory: rca-tool/tests
      
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: rca-tool/tests/test-results/
        retention-days: 30
